steps:
# - name: node
#   entrypoint: npm
#   args: ['install']
# https://cloud.google.com/build/docs/building/build-python
# - name: python
#   entrypoint: pip
#   args: ["install", "-r", "requirements.txt", "--user"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: '/bin/bash'
  args:
  - gcloud
  - builds
  - submit
  - --pack
  - image=gcr.io/$PROJECT_ID/youtubeapi:$COMMIT_SHA
